/** Declaration file generated by dts-gen */

export function colorStringify(obj: any, filter: any, indent: any, level: any): any;
export function colorStringify(obj: any, filter: any, indent: any): any;

export function parse(p0: any, p1: any): any;
export function parse(p0: any): any;

export function stringify(p0: any, p1: any, p2: any): any;

export namespace colorStringify {
    const prototype: {
    };

}

